### ISSUE TITLE
Feature: Show/Hide Screens

### ISSUE THREAD

**Issue by nwittwer** [nwittwer/reflex#161]
Ability to hide or show a screen on the canvas. Most likely makes sense in the right-click context menu for the sidebar and when clicking on a screen.

1. Add menu item to context menu to Show or Hide screen (should change title based on its current state)
2. Add Vuex Store property to artboards that defines their show/hide state
3. Add Vuex Store methods to toggle the state of the hidden/shown artboard

**Comment by emilkowalski** [comment]
Hi, can I take this one? :)

**Comment by nwittwer** [comment]
@emilkowalski Sure! :) Let me know if you run into any issues getting it running or finding things.

**Comment by emilkowalski** [comment]
@nwittwer I have managed to implement this feature, but forgot to branch off from dev, that's why I closed the pull request. I've branched off from dev now, but when I run yarn run dev, im getting an error: 
"Cannot read property 'length' of undefined"
It's about artboards.length.
Any idea how I can fix it so that I can implement my solution? :)

**Comment by nwittwer** [comment]
@emilkowalski Sorry about the late comment about branching from `dev`, I'll try and update the readme to make that more straightforward.

To fix that other issue you mentioned, try clearing your local storage by opening the DevTools > Application > Local Storage > file:// > and then delete the Reflex key. After reloading the app it should work again. I'd like to add an OS menu item to easily delete this, because I think this error happens when the localStorage data model has changed. It is a migration issue. Please let me know if it isn't fixed after that.

I haven't been able to try it out yet, but I think your solution seems good! Please go ahead and try the fix and then make another PR :)
