### ISSUE TITLE
[Discussion] Improve installation & update process

### ISSUE THREAD

**Issue by nwittwer** [nwittwer/reflex#63]
Tool considerations:
- [Homebrew Cask](https://github.com/Homebrew/homebrew-cask)
- [NWJS Docs: recommended auto-update tools](http://docs.nwjs.io/en/latest/For%20Users/Advanced/Autoupdates/#autoupdates)

Auto-updates:
- [x] Ability to download delta updates (only what's changed)

Other considerations:
- [x] Mac + Windows support?
- [x] Auto-updates?

**Comment by cbourgois** [comment]
Homebrew cask PR : https://github.com/Homebrew/homebrew-cask/pull/52679

**Comment by cbourgois** [comment]
Hi @nwitter,

Yes, if the `cask` PR is merged a new PR should be done later to update the download url format. If the shift release url format change before `cask` PR merge, we should update it ;)

**Comment by nwittwer** [comment]
@cbourgois Sounds good, I'll comment on here if the 0.3.0 release happens before then!
